# Generated by Django 4.2.4 on 2023-08-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('punct', models.CharField(max_length=10, verbose_name='Пункт приложени')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medic_works', to='company.company')),
            ],
            options={
                'verbose_name': 'Работа, требующая медосмотра',
                'verbose_name_plural': 'Работы, требующие медосмотров',
                'ordering': ['name'],
            },
        ),
    ]
