# Generated by Django 4.2.4 on 2023-08-31 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_medicwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Химические'), (2, 'Биологические'), (3, 'Пыли и аэрозоли'), (4, 'Физические'), (5, 'Тяжесть'), (6, 'Напряженность')], verbose_name='Группа')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('punct', models.CharField(max_length=10, verbose_name='Пункт приложения')),
                ('danger_class', models.PositiveSmallIntegerField(choices=[(0, 'Не применяется'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='Класс опасности')),
                ('is_allergen', models.BooleanField(default=False, verbose_name='Аллерген')),
                ('is_carcinogen', models.BooleanField(default=False, verbose_name='Канцероген')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='company.company')),
            ],
            options={
                'verbose_name': 'Вредный или опасный производственный фактор',
                'verbose_name_plural': 'Вредные и опасные производственные факторы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='dangerouswork',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicwork',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicwork',
            name='punct',
            field=models.CharField(max_length=10, verbose_name='Пункт приложения'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='FactorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_class', models.CharField(choices=[('2', 'Condition 2'), ('3.1', 'Condition 3 1'), ('3.2', 'Condition 3 2'), ('3.3', 'Condition 3 3'), ('3.4', 'Condition 3 4'), ('4', 'Condition 4')], max_length=250, verbose_name='Класс условий')),
                ('is_need_prev_medical', models.BooleanField(default=False, verbose_name='Необходим предварительный медосмотр')),
                ('medical_period', models.SmallIntegerField(blank=True, choices=[(None, 'Не требуется'), (1, '1 год'), (2, '2 года'), (3, '3 года')], null=True, verbose_name='Периодичность медосмотров')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='company.factor', verbose_name='Фактор')),
            ],
            options={
                'verbose_name': 'Класс условий труда',
                'verbose_name_plural': 'Классы условий труда',
                'ordering': ['factor'],
                'unique_together': {('factor', 'condition_class')},
            },
        ),
    ]
