# Generated by Django 4.2.4 on 2023-08-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_medicwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=15, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа вредных и опасных производственных факторов',
                'verbose_name_plural': 'Группа вредных и опасных производственных факторов',
            },
        ),
        migrations.AlterField(
            model_name='dangerouswork',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicwork',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicwork',
            name='punct',
            field=models.CharField(max_length=10, verbose_name='Пункт приложения'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('punct', models.CharField(max_length=10, verbose_name='Пункт приложения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='company.company')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factors', to='company.factorgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Вредный или опасный производственный фактор',
                'verbose_name_plural': 'Вредные и опасные производственные факторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FactorCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_class', models.CharField(choices=[('2', '2 - Допустимые'), ('3.1', '3.1 - Вредные первой степени'), ('3.1', '3.2 - Вредные второй степени'), ('3.1', '3.3 - Вредные третьей степени'), ('3.1', '3.4 - Вредные четвертой степени'), ('4', 'Опасные')], max_length=250, verbose_name='Класс условий')),
                ('is_need_prev_medical', models.BooleanField(default=True, verbose_name='Необходим предварительный медосмотр')),
                ('medical_period', models.PositiveSmallIntegerField(choices=[(1, '1 Год'), (2, '2 Года'), (3, '3 Года')], default=2, verbose_name='Периодичность медосмотров')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='company.factor', verbose_name='Фактор')),
            ],
            options={
                'verbose_name': 'Класс условий труда',
                'verbose_name_plural': 'Классы условий труда',
                'ordering': ['factor'],
                'unique_together': {('factor', 'condition_class')},
            },
        ),
    ]
