# Generated by Django 4.2.4 on 2023-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_factorgroup_alter_dangerouswork_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorcondition',
            name='condition_class',
            field=models.CharField(choices=[('2', '2 - Допустимые'), ('3.1', '3.1 - Вредные первой степени'), ('3.2', '3.2 - Вредные второй степени'), ('3.3', '3.3 - Вредные третьей степени'), ('3.4', '3.4 - Вредные четвертой степени'), ('4', '4 - Опасные')], max_length=250, verbose_name='Класс условий'),
        ),
        migrations.AlterField(
            model_name='factorcondition',
            name='is_need_prev_medical',
            field=models.BooleanField(default=False, verbose_name='Необходим предварительный медосмотр'),
        ),
        migrations.AlterField(
            model_name='factorcondition',
            name='medical_period',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не требуется'), (1, '1 год'), (2, '2 года'), (3, '3 года')], default=0, verbose_name='Периодичность медосмотров'),
        ),
    ]
