# Generated by Django 4.2.4 on 2023-09-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_medicwork_medical_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorcondition',
            options={'ordering': ['factor', 'condition_class'], 'verbose_name': 'Класс условий труда', 'verbose_name_plural': 'Классы условий труда'},
        ),
        migrations.AlterField(
            model_name='factorcondition',
            name='condition_class',
            field=models.CharField(choices=[('2', '2'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4', '4')], max_length=3, verbose_name='Класс условий труда'),
        ),
    ]
