# Generated by Django 4.2.4 on 2023-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_workplace_workplacefactor_workplace_factors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['department', 'name'], 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='workplace',
            name='extra_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('department', 'name')},
        ),
    ]
