# Generated by Django 4.2.4 on 2023-09-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_workplace_dangerous_works_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplacefactor',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='workplacefactor',
            name='workplace',
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
        migrations.DeleteModel(
            name='WorkplaceFactor',
        ),
    ]
