# Generated by Django 4.2.4 on 2023-09-16 20:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0011_remove_workplacefactor_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('extra_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Дополнительное описание')),
                ('code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Код должен соответствовать шаблону XXXX-XXX (X - число)', regex='^\\d{4}-\\d{3}$')], verbose_name='Код должности/профессии')),
                ('is_office_worker', models.BooleanField(default=False, editable=False, verbose_name='Должность служащего')),
                ('is_need_internship', models.BooleanField(default=False, verbose_name='Требуется стажировка')),
                ('is_need_knowledge_test', models.BooleanField(default=False, verbose_name='Требуется проверка знаний')),
                ('knowledge_test_period', models.SmallIntegerField(blank=True, null=True, verbose_name='Периодичность проверки знаний в месяцах')),
                ('dangerous_works', models.ManyToManyField(blank=True, to='company.dangerouswork', verbose_name='Работы с повышенной опасностью')),
                ('department', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='workplaces', to='company.department')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkplaceFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_class', models.CharField(choices=[('2', '2'), ('3.1', '3.1'), ('3.2', '3.2'), ('3.3', '3.3'), ('3.4', '3.4'), ('4', '4')], max_length=3, verbose_name='Класс условий труда')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.factor', verbose_name='Фактор')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace')),
            ],
            options={
                'ordering': ['factor__name'],
                'unique_together': {('workplace_id', 'factor_id')},
            },
        ),
        migrations.AddField(
            model_name='workplace',
            name='factors',
            field=models.ManyToManyField(through='workplace.WorkplaceFactor', to='company.factor', verbose_name='Вредные и опасные производственные факторы'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='medic_works',
            field=models.ManyToManyField(blank=True, to='company.medicwork', verbose_name='Работы, требующие медосмотров'),
        ),
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('department', 'name')},
        ),
    ]
