# Generated by Django 4.2.4 on 2023-09-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0011_remove_workplacefactor_factor_and_more'),
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(max_length=10, unique=True, verbose_name='Табельный номер')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('hiring_date', models.DateField(verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашний адрес')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.company')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Предварительный'), (2, 'Периодический'), (3, 'Внеплановый')], verbose_name='Вид')),
                ('date', models.DateField(verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Медицинский осмотр',
                'verbose_name_plural': 'Медицинские осмотр',
                'ordering': ['employee', 'date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Первичная'), (2, 'Периодическая'), (3, 'Повторная'), (4, 'Внеплановая')], verbose_name='Вид')),
                ('date', models.DateField(verbose_name='Дата')),
                ('protocol_number', models.PositiveIntegerField(verbose_name='Номер протокола')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_tests', to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Проверка знаний',
                'verbose_name_plural': 'Проверки знаний',
                'ordering': ['employee', 'date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала работы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.workplace', verbose_name='Рабочее место')),
            ],
            options={
                'ordering': ['date_start'],
                'unique_together': {('employee_id', 'workplace_id')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='workplaces',
            field=models.ManyToManyField(blank=True, through='employee.EmployeeWorkplace', to='workplace.workplace', verbose_name='Рабочие места'),
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Вводный'), (2, 'Первичный'), (3, 'Повторный'), (4, 'Целевой'), (5, 'Внеплановый')], verbose_name='Вид')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Инструктаж',
                'verbose_name_plural': 'Инструктажи',
                'ordering': ['employee', 'date'],
            },
        ),
    ]
